//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public long billNo { get; set; }
        public string dateBill { get; set; }
        public string toName { get; set; }
        public string addLine1 { get; set; }
        public string addLine2 { get; set; }
        public string addLine3 { get; set; }
        public string transportMode { get; set; }
        public string vehicleNoBill { get; set; }
        public string placeOfDeliveryBill { get; set; }
        public string materialDescription { get; set; }
        public string netWeightQty { get; set; }
        public Nullable<double> rateBill { get; set; }
        public Nullable<double> amountBill { get; set; }
        public Nullable<double> totalAmountBill { get; set; }
        public string totalInWords { get; set; }
        public Nullable<double> cgst { get; set; }
        public Nullable<double> sgst { get; set; }
        public Nullable<double> mainTotal { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
