//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comport
    {
        public long id { get; set; }
        public string port { get; set; }
        public string buadRate { get; set; }
        public string parity { get; set; }
        public string dataBit { get; set; }
        public string stopBit { get; set; }
    }
}
