//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class party_details
    {
        public party_details()
        {
            this.vehicles = new HashSet<vehicle>();
        }
    
        public long partyId { get; set; }
        public string partyType { get; set; }
        public string partyName { get; set; }
        public Nullable<long> mobile { get; set; }
        public Nullable<long> telephone { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public Nullable<int> pincode { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string email { get; set; }
        public string pancard { get; set; }
        public string gstIn { get; set; }
        public string createBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
    
        public virtual ICollection<vehicle> vehicles { get; set; }
    }
}
